---
  - name: Обновление pip
    command: "{{ python_environment_directory }}/bin/pip install --upgrade pip"
    register: result_update_pip

  - name: Debug
    debug:
      var: result_update_pip

  - name: Генерация файла со списком устанавливаемых через pip пакетов
    template:
      src: requirements-pip.j2
      dest: "{{ python_environment_directory }}/requirements-pip"
      mode: "0644"

  - name: Обновление пакетов Python через pip
    command: "{{ python_environment_directory }}/bin/pip install -r {{ python_environment_directory }}/requirements-pip"
    register: result_install_packages_from_pip
    when: "'pip' in python.packages"

  - name: Debug
    debug:
      var: result_install_packages_from_pip
    when: "'pip' in python.packages"