---
  - name: Проверка наличия каталога "{{ terminal_directory }}"
    file:
      path: "{{ terminal_directory }}"
      state: directory
      mode: '0755'

  - include: python.yml
    when: "python and python_environment_path is not defined"

  - include: init.yml

  - include: history.yml
    when: history

  - name: Сохраняются параметры терминала {{ uid }}
    set_fact:
      workspace_vscode_terminals: "{{ workspace_vscode_terminals|default([]) + [{'uid': uid, 'name': title, 'description': description, 'focus': focus, 'command': ' source ' + terminal_directory + '/init'}]}}"
    changed_when: yes
    notify: Генерация файла 'terminals.json'
