---
  - name: "Установка виртуального окружения Python версии {{ python.version }} в терминал {{ uid }}"
    include_role:
      name: mondrik.conda-env-python
    vars:
      python_environment_directory: "{{ terminal_directory }}/python"
      python_environment_version: "{{ python.version }}"
      python_environment_origin: "{{ python.origin }}"
      python_environment_packages_pip: "{{ python.packages.pip | default([]) }}"
      python_environment_packages_conda: "{{ python.packages.conda | default({}) }}"

  - name: Задание пути к интерпретатору Python
    set_fact:
      python_environment_path: "{{ terminal_directory }}/python"
