---
  - name: "Установка виртуального окружения Python версии {{ python.version }} в терминал {{ uid }}"
    debug:
      var: python

  - name: Создание каталога для виртуального окружения Python
    file:
      path: "{{ terminal_directory }}/python"
      state: directory
      mode: 0755

  - name: Создание виртуального окружения Python с использованием conda
    command: "{{ python.origin }}/bin/conda create --quiet --prefix {{ terminal_directory }}/python --yes --copy --no-default-packages python=={{ python.version }}"
    register: result_install_python_from_conda

  - name: Генерация файла со списком устанавливаемых пакетов
    template:
      src: conda-environment.yml.j2
      dest: "{{ terminal_directory }}/conda-environment.yml"
      mode: "0644"
    when: "'conda' in python.packages"

  - name: Обновление пакетов в виртуальном окружении Python с использованием conda
    command: "{{ python.origin }}/bin/conda env update --file {{ terminal_directory }}/conda-environment.yml --quiet --prefix {{ terminal_directory }}/python"
    register: result_update_python_packages
    when: "'conda' in python.packages"

  - name: Debug
    debug:
      var: result_install_python_from_conda
    when: "'conda' in python.packages"
