---
  - name: Создание каталога для виртуального окружения Python
    file:
      path: "{{ python_environment_directory }}"
      state: directory
      mode: 0755

  - name: Создание виртуального окружения Python с использованием conda
    command: "{{ python_environment_origin }}/bin/conda create --quiet --prefix {{ python_environment_directory }} --yes --copy --no-default-packages python=={{ python_environment_version }}"
    register: result_install_python_from_conda

  - include: packages/conda.yml
    when: python_environment_packages_conda

  - include: packages/pip.yml
    when: python_environment_packages_pip
