---
  - name: Сохраняются переменные
    set_fact:
      workspace_vscode_directory: "{{ workspace_directory }}/.vscode"

  - name: Проверка наличия каталога "{{ workspace_vscode_directory }}"
    file:
      path: "{{ workspace_vscode_directory }}"
      state: directory
      mode: '0755'

  - name: Генерация файла 'code-workspaces'
    template:
      src: code-workspace.j2
      dest: "{{ workspace_vscode_directory }}/{{ workspace_name }}.code-workspace"
      mode: "0755"

  - include: python.yml
    when: python

  - include: settings.yml
