---
  - set_fact:
      settings: "{{ settings + ['\"git.ignoreLimitWarning\": \"{{ git.ignoreLimitWarning | default(\"false\")}}\"'] }}"
    when: git

  - name: Генерация файла 'settings.json'
    template:
      src: settings.json.j2
      dest: "{{ workspace_vscode_directory }}/settings.json"
      mode: "0755"