---
  - include: env/conda.yml

  - name: Обновление pip
    command: "{{ terminal_directory }}/python/bin/pip install --upgrade pip"
    register: result_update_pip

  - name: Debug
    debug:
      var: result_update_pip

  - name: Генерация файла со списком устанавливаемых через pip пакетов
    template:
      src: requirements-pip.j2
      dest: "{{ terminal_directory }}/requirements-pip"
      mode: "0644"

  - name: Обновление пакетов Python через pip
    command: "{{ terminal_directory }}/python/bin/pip install -r {{ terminal_directory }}/requirements-pip"
    register: result_install_packages_from_pip

  - name: Debug
    debug:
      var: result_install_packages_from_pip