---
  - name: Проверка наличия каталога '{{ install_dir }}'
    file:
      path: "{{ install_dir }}"
      state: directory
      mode: '0755'

  - name: "Обновление пакетов Anaconda (версия Python: {{ python_version }})"
    command: bin/conda update --yes anaconda
    args:
      chdir: "{{ install_dir }}"
    register: result
